SCENARIOS = [ {"label": "Resting session", 
"participant_id": "P001", 
"scenario": "resting", 
"seed": 1, 
"number_of_windows": 10}, 
{"label": "Moderate activity session", 
 "participant_id": "P002", 
 "scenario": "moderate_activity", 
 "seed": 2, 
 "number_of_windows": 10}, 
 {"label": "High activity session", 
  "participant_id": "P003", 
  "scenario": "high_activity", 
  "seed": 3, "number_of_windows": 10}, 
  {"label": "Recovery session", 
   "participant_id": "P004", 
   "scenario": "recovery", 
   "seed": 4, 
   "number_of_windows": 12}, 
   {"label": "Poor quality / invalid data session", 
    "participant_id": "P005", 
    "scenario": "poor_quality", 
    "seed": 5, 
    "number_of_windows": 12}, 
    ]


